-- MySQL Script generated by MySQL Workbench
-- Mon Jun 29 19:20:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(225) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  `email` VARCHAR(225) NOT NULL,
  `photo` VARCHAR(225) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `id_question` INT NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `quest_content` VARCHAR(1000) NOT NULL,
  `create_time` TIMESTAMP NULL,
  `update_time` TIMESTAMP NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_question`, `user_id_user`),
  INDEX `fk_question_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_question_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answer` (
  `id_answer` INT NOT NULL AUTO_INCREMENT,
  `answer_content` TEXT NOT NULL,
  `create_time` TIMESTAMP NULL,
  `update_time` TIMESTAMP NULL,
  `question_id_question` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_answer`, `question_id_question`, `user_id_user`),
  INDEX `fk_answer_question1_idx` (`question_id_question` ASC) VISIBLE,
  INDEX `fk_answer_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question_id_question`)
    REFERENCES `mydb`.`question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `comment_content` TEXT NOT NULL,
  `create_time` TIMESTAMP NULL,
  `update_time` TIMESTAMP NULL,
  `answer_id_answer` INT NOT NULL,
  `question_id_question` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_comment`, `answer_id_answer`, `question_id_question`, `user_id_user`),
  INDEX `fk_comment_answer1_idx` (`answer_id_answer` ASC) VISIBLE,
  INDEX `fk_comment_question1_idx` (`question_id_question` ASC) VISIBLE,
  INDEX `fk_comment_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_comment_answer1`
    FOREIGN KEY (`answer_id_answer`)
    REFERENCES `mydb`.`answer` (`id_answer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_question1`
    FOREIGN KEY (`question_id_question`)
    REFERENCES `mydb`.`question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vote` (
  `id_vote` INT NOT NULL AUTO_INCREMENT,
  `user_id_user` INT NOT NULL,
  `comment_id_comment` INT NOT NULL,
  `question_id_question` INT NOT NULL,
  `answer_id_answer` INT NOT NULL,
  PRIMARY KEY (`id_vote`, `user_id_user`, `comment_id_comment`, `question_id_question`, `answer_id_answer`),
  INDEX `fk_vote_user_idx` (`user_id_user` ASC) VISIBLE,
  INDEX `fk_vote_comment1_idx` (`comment_id_comment` ASC) VISIBLE,
  INDEX `fk_vote_question1_idx` (`question_id_question` ASC) VISIBLE,
  INDEX `fk_vote_answer1_idx` (`answer_id_answer` ASC) VISIBLE,
  CONSTRAINT `fk_vote_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_comment1`
    FOREIGN KEY (`comment_id_comment`)
    REFERENCES `mydb`.`comment` (`id_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_question1`
    FOREIGN KEY (`question_id_question`)
    REFERENCES `mydb`.`question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_answer1`
    FOREIGN KEY (`answer_id_answer`)
    REFERENCES `mydb`.`answer` (`id_answer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
